server:
  port: 80
  context-path: /
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zmq_pro?serverTimezone=GMT%2B8&useSSL=true&characterEncoding=utf8
    username: root
    password: 1237890
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-request-size: 500MB
logging:
  level: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mqz.pojo
